"use strict";
let miNumero = 10;
miNumero = 10 + 10;
miNumero = 2.5;
console.log(miNumero);
let booleano = true;
booleano = false;
//booleano = 3;
//booleano = null;
let encendido = true;
console.log('encendido es:', encendido);
console.log('encendido es:', { encendido });
encendido = true && false;
console.log(encendido);
let normal = 'hola';
normal = 10;
normal = true;
normal = 11.25;
console.log('Normal: ', normal);
